### ISSUE TITLE
WebpackFunction construct throw an exception on windows

### ISSUE THREAD

**Issue by Freddv2** [masahirompp/aws-cdk-webpack-lambda-function#4]
The library doesn't seem to work on windows environnement. When I `cdk synth` with the `WebpackFunction` construct:
```
const func = new WebpackFunction(this,id,{
            entry: '../functions/portfolio/src/lambda.ts',
            config: '../functions/portfolio/webpack.config.js'
        })
```

I get this weird error:

```
Error: spawnSync C:\serverless-rest-api-typescript\cdk\node_modules\webpack-cli\bin\cli.js UNKNOWN
    at Object.spawnSync (internal/child_process.js:1041:20)
    at Object.spawnSync (child_process.js:616:24)
    at Builder.build (C:\serverless-rest-api-typescript\cdk\node_modules\aws-cdk-webpack-lambda-function\lib\builder.js:29:41)
    at preProcess (C:\serverless-rest-api-typescript\cdk\node_modules\aws-cdk-webpack-lambda-function\lib\function.js:60:13)
    at new WebpackFunction (C:\serverless-rest-api-typescript\cdk\node_modules\aws-cdk-webpack-lambda-function\lib\function.js:14:66)
    at new PortfolioCRUDRestAPI (C:\serverless-rest-api-typescript\cdk\lib\portfolio-crud-api.ts:21:22)
    at new AppStack (C:\serverless-rest-api-typescript\cdk\lib\app-stack.ts:8:5)
    at Object.<anonymous> (C:\serverless-rest-api-typescript\cdk\bin\cdk.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (C:\serverless-rest-api-typescript\cdk\node_modules\ts-node\src\index.ts:858:23)
```

**Comment by masahirompp** [comment]
@Freddv2 I merged your pull request. please upgrade to aws-cdk-webpack-lambda-function@0.4.0. Thanks.
